kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/maximilianoPizarro/jhipster-devspace'
  name: delivery
  labels:
    app: delivery
    app.kubernetes.io/component: delivery
    app.kubernetes.io/instance: delivery
    app.kubernetes.io/name: delivery
    app.kubernetes.io/part-of: delivery
    app.openshift.io/runtime: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: delivery
        app.openshift.io/runtime: python
        deployment: delivery
    spec:
      containers:
        - name: delivery
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
